name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
    - name: WML Lint
      uses: czyzby/wesnoth-wml-linter@v1
