name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint WML
      uses: czyzby/wesnoth-wml-linter@v1
    - name: Verify images
      uses: czyzby/wesnoth-png-optimizer@v1
